@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle bold
hide empty members
hide empty methods
title "ID Centralization System"

class "IDCSys_Encode"
package "ID Centralization System"{
IDCSys_Encode -- "IDCSys_Database"
class "IDCSys_Database" << idcsys_db >>
IDCSys_Database : +active_database
class "IDCSys_Decode" << idcsys_decode >>
IDCSys_Database -- IDCSys_Decode
IDCSys_Decode : +decode_encryption: card_data
class "IDCSys_Acquire" << idcsys_core >>
IDCSys_Decode -- RFIDSys_Acquire
IDCSys_Acquire : +database_search(): decoded_card_data
IDCSys_Acquire : +get_from_database(name,age)
IDCSys_Acquire : +get_from_database(name,address)
IDCSys_Acquire : +get_from_database(name,birth_date)
IDCSys_Acquire : +get_from_database(name,contact_number)
IDCSys_Acquire : +get_from_database(name,blood_type)
IDCSys_Acquire : +get_from_database(name,nationality)
}

IDCSys_Acquire "1"--"*" API
class "API" << idcsys_menu >>
API : +main_program
API : +receive_data_from_IDCSys()
API : +display_data_to_user()

@enduml
