@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle bold
hide empty members
hide empty methods
title "RFID Identification System"

class "RFIDSys_Encode"
package "RFID Identification System"{
RFIDSys_Encode -- "RFIDSys_Database"
class "RFIDSys_Database" << rfidsys_db >>
RFIDSys_Database : +active_database
class "RFIDSys_Decode" << rfidsys_decode >>
RFIDSys_Database -- RFIDSys_Decode
RFIDSys_Decode : +decode_encryption: card_data
class "RFIDSys_Acquire" << rfidsys_core >>
RFIDSys_Decode -- RFIDSys_Acquire
RFIDSys_Acquire : +database_search(): decoded_card_data
RFIDSys_Acquire : +get_from_database(name,age)
RFIDSys_Acquire : +get_from_database(name,address)
RFIDSys_Acquire : +get_from_database(name,birth_date)
RFIDSys_Acquire : +get_from_database(name,contact_number)
RFIDSys_Acquire : +get_from_database(name,blood_type)
RFIDSys_Acquire : +get_from_database(name,nationality)
}

RFIDSys_Acquire "1"--"*" API
class "API" << rfidsys_menu >>
API : +main_program
API : +receive_data_from_RFIDSys()
API : +display_data_to_user()

@enduml